#!/usr/bin/env bash
# setup_respeaker.sh
# One-shot setup for the ReSpeaker Mic Array v2.0 on RPi5 / Ubuntu 24.04.
# Installs system + Python deps, then configures ALSA + PulseAudio so audio
# input AND output default to the ReSpeaker (output exits its 3.5mm jack).

set -euo pipefail

echo "=== ReSpeaker Mic Array v2.0 setup ==="

# --- 1. System packages ----------------------------------------------------
echo "[1/4] Installing system packages..."
sudo apt-get update
sudo apt-get install -y \
    alsa-utils \
    pulseaudio-utils \
    portaudio19-dev \
    python3-pyaudio \
    libasound2-plugins

# --- 2. Detect the ReSpeaker ALSA card index -------------------------------
echo "[2/4] Detecting ReSpeaker card..."
# Match either "ReSpeaker" or "Mic Array" — vendor strings vary by firmware
CARD_INDEX=$(aplay -l 2>/dev/null | awk -F'[ :]' '/[Rr]e[Ss]peaker|Mic Array/ {print $2; exit}')

if [[ -z "${CARD_INDEX:-}" ]]; then
    echo "ERROR: ReSpeaker not found in 'aplay -l' output."
    echo "Run 'lsusb' (look for 2886:0018) and 'dmesg | tail' to debug."
    echo "Most common cause: charge-only USB cable. Swap for a data cable."
    exit 1
fi

echo "  Found ReSpeaker at card index ${CARD_INDEX}"
aplay -l   | grep -E "card ${CARD_INDEX}:" || true
arecord -l | grep -E "card ${CARD_INDEX}:" || true

# --- 3. Write ~/.asoundrc to make ReSpeaker the default ALSA device --------
echo "[3/4] Writing ~/.asoundrc..."
ASOUNDRC="${HOME}/.asoundrc"
if [[ -f "${ASOUNDRC}" ]]; then
    cp "${ASOUNDRC}" "${ASOUNDRC}.bak.$(date +%s)"
    echo "  Backed up existing .asoundrc"
fi

cat > "${ASOUNDRC}" <<EOF
# Auto-generated by setup_respeaker.sh
# Routes default ALSA playback + capture to the ReSpeaker Mic Array v2.0.
# Output physically exits the ReSpeaker's 3.5mm headphone jack.

pcm.!default {
    type asym
    playback.pcm "plug:respeaker_out"
    capture.pcm  "plug:respeaker_in"
}

pcm.respeaker_out {
    type plug
    slave {
        pcm "hw:${CARD_INDEX},0"
    }
}

pcm.respeaker_in {
    type plug
    slave {
        pcm "hw:${CARD_INDEX},0"
    }
}

ctl.!default {
    type hw
    card ${CARD_INDEX}
}
EOF
echo "  Wrote ${ASOUNDRC}"

# --- 4. If PulseAudio/PipeWire is running, set defaults there too ----------
echo "[4/4] Configuring PulseAudio/PipeWire defaults (if running)..."
if command -v pactl >/dev/null 2>&1 && pactl info >/dev/null 2>&1; then
    SINK=$(pactl list short sinks   | awk '/[Rr]e[Ss]peaker|Mic_Array|SEEED/ {print $2; exit}')
    SRC=$( pactl list short sources | awk '/[Rr]e[Ss]peaker|Mic_Array|SEEED/ && $0 !~ /\.monitor$/ {print $2; exit}')

    if [[ -n "${SINK:-}" ]]; then
        pactl set-default-sink "${SINK}"
        echo "  Default sink   -> ${SINK}"
    else
        echo "  (no PulseAudio sink found for ReSpeaker — ALSA defaults will still apply)"
    fi
    if [[ -n "${SRC:-}" ]]; then
        pactl set-default-source "${SRC}"
        echo "  Default source -> ${SRC}"
    fi
else
    echo "  PulseAudio/PipeWire not running — using pure-ALSA config only."
fi

echo
echo "=== Done. ==="
echo "Quick smoke test:"
echo "  speaker-test -D default -c 2 -t sine -l 1   # hear sine via 3.5mm jack"
echo "  arecord -D default -r 16000 -c 1 -f S16_LE -d 5 /tmp/t.wav && aplay /tmp/t.wav"
echo "Then run: python3 respeaker_test.py"
